services:
    app:
        container_name: command-app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
networks:
    lion:
        driver: bridge
